-- CIVENTRAL DRRM Module 3: Incident Reporting & Response Log
-- Phase 8A database foundation. This migration creates no incident records.

begin;

create table if not exists public.drrm_incident_types (
    incident_type_id smallint generated by default as identity primary key,
    code text not null,
    label text not null,
    sort_order smallint not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),

    constraint drrm_incident_types_code_unique unique (code),
    constraint drrm_incident_types_sort_order_unique unique (sort_order),
    constraint drrm_incident_types_code_format check (
        code = upper(code) and code ~ '^[A-Z][A-Z0-9_]*$'
    ),
    constraint drrm_incident_types_label_required check (btrim(label) <> ''),
    constraint drrm_incident_types_sort_order_positive check (sort_order > 0)
);

create table if not exists public.drrm_incident_severities (
    severity_id smallint generated by default as identity primary key,
    code text not null,
    label text not null,
    severity_rank smallint not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),

    constraint drrm_incident_severities_code_unique unique (code),
    constraint drrm_incident_severities_rank_unique unique (severity_rank),
    constraint drrm_incident_severities_code_check check (
        code in ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')
    ),
    constraint drrm_incident_severities_label_required check (btrim(label) <> ''),
    constraint drrm_incident_severities_rank_check check (severity_rank between 1 and 4)
);

create sequence if not exists public.drrm_incident_number_seq
    as bigint
    start with 1
    increment by 1
    minvalue 1
    no maxvalue
    cache 20;

create or replace function public.next_drrm_incident_number()
returns text
language plpgsql
volatile
security definer
set search_path = pg_catalog, public
as $function$
declare
    sequence_value bigint;
begin
    sequence_value := nextval('public.drrm_incident_number_seq');
    return 'INC-' || to_char(current_date, 'YYYY') || '-' || lpad(sequence_value::text, 6, '0');
end;
$function$;

create table if not exists public.drrm_incidents (
    id uuid primary key default gen_random_uuid(),
    incident_number text not null default public.next_drrm_incident_number(),
    incident_type_id smallint not null,
    title text not null,
    description text not null,
    severity_id smallint not null,
    status text not null default 'SUBMITTED',
    reported_at timestamptz not null default now(),

    reporter_type text not null,
    reporter_reference text null,
    barangay_id uuid null,
    location_description text not null,
    latitude numeric(9, 6) null,
    longitude numeric(9, 6) null,

    source text not null,
    verification_status text not null default 'PENDING',
    verified_at timestamptz null,
    verified_by_reference text null,

    assigned_department_reference text null,
    assigned_user_reference text null,
    created_by_reference text null,

    resolved_at timestamptz null,
    closed_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint drrm_incidents_incident_number_unique unique (incident_number),
    constraint drrm_incidents_incident_type_id_fkey
        foreign key (incident_type_id)
        references public.drrm_incident_types (incident_type_id)
        on delete restrict,
    constraint drrm_incidents_severity_id_fkey
        foreign key (severity_id)
        references public.drrm_incident_severities (severity_id)
        on delete restrict,
    constraint drrm_incidents_barangay_id_fkey
        foreign key (barangay_id)
        references public.barangays (barangay_id)
        on delete restrict,
    constraint drrm_incidents_incident_number_format check (
        incident_number ~ '^INC-[0-9]{4}-[0-9]{6,}$'
    ),
    constraint drrm_incidents_title_required check (
        btrim(title) <> '' and char_length(title) <= 180
    ),
    constraint drrm_incidents_description_required check (
        btrim(description) <> '' and char_length(description) <= 10000
    ),
    constraint drrm_incidents_status_check check (
        status in (
            'SUBMITTED', 'UNDER_REVIEW', 'VERIFIED', 'ASSIGNED',
            'RESPONDING', 'RESOLVED', 'CLOSED', 'REJECTED'
        )
    ),
    constraint drrm_incidents_reporter_type_check check (
        reporter_type in (
            'CITIZEN', 'EMPLOYEE', 'BARANGAY_CONTACT',
            'EXTERNAL_CONTACT', 'ANONYMOUS'
        )
    ),
    constraint drrm_incidents_reporter_reference_length check (
        reporter_reference is null or (
            btrim(reporter_reference) <> '' and char_length(reporter_reference) <= 200
        )
    ),
    constraint drrm_incidents_location_required check (
        btrim(location_description) <> '' and char_length(location_description) <= 1000
    ),
    constraint drrm_incidents_coordinate_pair_check check (
        (latitude is null and longitude is null)
        or (latitude is not null and longitude is not null)
    ),
    constraint drrm_incidents_latitude_check check (
        latitude is null or latitude between -90 and 90
    ),
    constraint drrm_incidents_longitude_check check (
        longitude is null or longitude between -180 and 180
    ),
    constraint drrm_incidents_source_check check (
        source in (
            'ADMIN', 'BARANGAY', 'DRRM_OFFICER',
            'CITIZEN_MOBILE', 'EXTERNAL_REFERENCE'
        )
    ),
    constraint drrm_incidents_verification_status_check check (
        verification_status in ('PENDING', 'IN_REVIEW', 'VERIFIED', 'REJECTED')
    ),
    constraint drrm_incidents_verification_fields_check check (
        (verification_status = 'VERIFIED' and verified_at is not null and verified_by_reference is not null)
        or (verification_status <> 'VERIFIED' and verified_at is null and verified_by_reference is null)
    ),
    constraint drrm_incidents_assignment_reference_length check (
        (assigned_department_reference is null or (
            btrim(assigned_department_reference) <> ''
            and char_length(assigned_department_reference) <= 200
        ))
        and (assigned_user_reference is null or (
            btrim(assigned_user_reference) <> ''
            and char_length(assigned_user_reference) <= 200
        ))
    ),
    constraint drrm_incidents_created_by_reference_length check (
        created_by_reference is null or (
            btrim(created_by_reference) <> '' and char_length(created_by_reference) <= 200
        )
    ),
    constraint drrm_incidents_resolution_time_check check (
        resolved_at is null or resolved_at >= reported_at
    ),
    constraint drrm_incidents_closure_time_check check (
        closed_at is null or (resolved_at is not null and closed_at >= resolved_at)
    )
);

create table if not exists public.drrm_incident_status_history (
    id uuid primary key default gen_random_uuid(),
    incident_id uuid not null,
    from_status text null,
    to_status text not null,
    changed_at timestamptz not null default now(),
    changed_by_reference text not null,
    notes text null,

    constraint drrm_incident_status_history_incident_id_fkey
        foreign key (incident_id)
        references public.drrm_incidents (id)
        on delete restrict,
    constraint drrm_incident_status_history_from_status_check check (
        from_status is null or from_status in (
            'SUBMITTED', 'UNDER_REVIEW', 'VERIFIED', 'ASSIGNED',
            'RESPONDING', 'RESOLVED', 'CLOSED', 'REJECTED'
        )
    ),
    constraint drrm_incident_status_history_to_status_check check (
        to_status in (
            'SUBMITTED', 'UNDER_REVIEW', 'VERIFIED', 'ASSIGNED',
            'RESPONDING', 'RESOLVED', 'CLOSED', 'REJECTED'
        )
    ),
    constraint drrm_incident_status_history_actor_required check (
        btrim(changed_by_reference) <> '' and char_length(changed_by_reference) <= 200
    ),
    constraint drrm_incident_status_history_notes_check check (
        notes is null or (
            btrim(notes) <> '' and char_length(notes) <= 2000
            and notes !~ '[<>]'
        )
    )
);

create table if not exists public.drrm_incident_assignments (
    id uuid primary key default gen_random_uuid(),
    incident_id uuid not null,
    department_reference text null,
    user_reference text null,
    assigned_at timestamptz not null default now(),
    assigned_by_reference text not null,
    notes text null,

    constraint drrm_incident_assignments_incident_id_fkey
        foreign key (incident_id)
        references public.drrm_incidents (id)
        on delete restrict,
    constraint drrm_incident_assignments_target_required check (
        department_reference is not null or user_reference is not null
    ),
    constraint drrm_incident_assignments_reference_check check (
        (department_reference is null or (
            btrim(department_reference) <> '' and char_length(department_reference) <= 200
        ))
        and (user_reference is null or (
            btrim(user_reference) <> '' and char_length(user_reference) <= 200
        ))
        and btrim(assigned_by_reference) <> ''
        and char_length(assigned_by_reference) <= 200
    ),
    constraint drrm_incident_assignments_notes_check check (
        notes is null or (
            btrim(notes) <> '' and char_length(notes) <= 2000
            and notes !~ '[<>]'
        )
    )
);

create table if not exists public.drrm_incident_response_logs (
    id uuid primary key default gen_random_uuid(),
    incident_id uuid not null,
    action_type text not null,
    message text not null,
    created_at timestamptz not null default now(),
    created_by_reference text not null,

    constraint drrm_incident_response_logs_incident_id_fkey
        foreign key (incident_id)
        references public.drrm_incidents (id)
        on delete restrict,
    constraint drrm_incident_response_logs_action_type_check check (
        action_type in (
            'REVIEW_NOTE', 'VERIFICATION_NOTE', 'ASSIGNMENT_NOTE',
            'DISPATCH_NOTE', 'RESPONSE_UPDATE', 'RESOLUTION_NOTE',
            'CLOSURE_NOTE', 'REJECTION_NOTE'
        )
    ),
    constraint drrm_incident_response_logs_message_check check (
        btrim(message) <> '' and char_length(message) <= 5000
        and message !~ '[<>]'
    ),
    constraint drrm_incident_response_logs_actor_required check (
        btrim(created_by_reference) <> '' and char_length(created_by_reference) <= 200
    )
);

comment on table public.drrm_incident_types is
    'Controlled, machine-readable categories for Module 3 incident records.';
comment on table public.drrm_incident_severities is
    'Incident-specific operational severity. It is intentionally separate from Module 4 warning/risk levels.';
comment on table public.drrm_incidents is
    'Observed or reported events. Incidents never activate or create early warnings automatically.';
comment on column public.drrm_incidents.reporter_reference is
    'Optional stable reference to an externally owned identity; no citizen profile or authentication data is copied here.';
comment on column public.drrm_incidents.barangay_id is
    'Optional validated Caloocan barangay reference. Coordinates, when present, use WGS84 / EPSG:4326.';
comment on column public.drrm_incidents.verification_status is
    'Only VERIFIED records may later be considered as governed evidence; no AI dataset export is performed by Module 3.';
comment on table public.drrm_incident_status_history is
    'Append-only audit history for every incident lifecycle transition.';
comment on table public.drrm_incident_assignments is
    'Assignment history containing references to MySQL-owned CIVENTRAL departments/users without copying those entities.';
comment on table public.drrm_incident_response_logs is
    'Plain-text operational response activity; arbitrary HTML is rejected.';

create index if not exists drrm_incidents_status_idx
    on public.drrm_incidents (status);
create index if not exists drrm_incidents_reported_at_idx
    on public.drrm_incidents (reported_at desc);
create index if not exists drrm_incidents_type_idx
    on public.drrm_incidents (incident_type_id);
create index if not exists drrm_incidents_severity_idx
    on public.drrm_incidents (severity_id);
create index if not exists drrm_incidents_barangay_idx
    on public.drrm_incidents (barangay_id)
    where barangay_id is not null;
create index if not exists drrm_incidents_resolved_at_idx
    on public.drrm_incidents (resolved_at desc)
    where resolved_at is not null;
create index if not exists drrm_incidents_source_idx
    on public.drrm_incidents (source);
create index if not exists drrm_incident_status_history_incident_idx
    on public.drrm_incident_status_history (incident_id, changed_at asc);
create index if not exists drrm_incident_assignments_incident_idx
    on public.drrm_incident_assignments (incident_id, assigned_at desc);
create index if not exists drrm_incident_response_logs_incident_idx
    on public.drrm_incident_response_logs (incident_id, created_at asc);

create or replace function public.set_module3_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $function$
begin
    new.updated_at = now();
    return new;
end;
$function$;

drop trigger if exists drrm_incidents_set_updated_at on public.drrm_incidents;
create trigger drrm_incidents_set_updated_at
before update on public.drrm_incidents
for each row execute function public.set_module3_updated_at();

create or replace function public.record_drrm_incident_submission()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
begin
    if new.status <> 'SUBMITTED'
       or new.verification_status <> 'PENDING'
       or new.verified_at is not null
       or new.verified_by_reference is not null
       or new.assigned_department_reference is not null
       or new.assigned_user_reference is not null
       or new.resolved_at is not null
       or new.closed_at is not null then
        raise exception using errcode = '23514', message = 'New incident records must enter through the submitted state.';
    end if;

    insert into public.drrm_incident_status_history (
        incident_id, from_status, to_status, changed_by_reference, notes
    ) values (
        new.id,
        null,
        'SUBMITTED',
        coalesce(new.created_by_reference, new.reporter_reference, 'SYSTEM:INGESTION'),
        null
    );
    return new;
end;
$function$;

drop trigger if exists drrm_incidents_record_submission on public.drrm_incidents;
create trigger drrm_incidents_record_submission
after insert on public.drrm_incidents
for each row execute function public.record_drrm_incident_submission();

create or replace function public.validate_drrm_incident_barangay()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
begin
    if new.barangay_id is null then
        return new;
    end if;

    if not exists (
        select 1
        from public.barangays as barangay
        where barangay.barangay_id = new.barangay_id
          and barangay.boundary_dataset_version_id = 'b386cd54-2288-423f-9b92-2092333333c1'::uuid
          and barangay.record_status = 'INACTIVE'
          and barangay.name <> 'Barangay 176'
    ) then
        raise exception using errcode = '23514', message = 'The incident barangay reference is not in the validated Caloocan catalog.';
    end if;

    return new;
end;
$function$;

drop trigger if exists drrm_incidents_validate_barangay on public.drrm_incidents;
create trigger drrm_incidents_validate_barangay
before insert or update of barangay_id on public.drrm_incidents
for each row execute function public.validate_drrm_incident_barangay();

create or replace function public.transition_drrm_incident(
    p_incident_id uuid,
    p_action text,
    p_actor_reference text,
    p_notes text default null,
    p_assigned_department_reference text default null,
    p_assigned_user_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
    incident_record public.drrm_incidents%rowtype;
    target_status text;
    log_action_type text;
begin
    p_action := upper(btrim(coalesce(p_action, '')));
    p_actor_reference := btrim(coalesce(p_actor_reference, ''));
    p_notes := nullif(btrim(coalesce(p_notes, '')), '');
    p_assigned_department_reference := nullif(btrim(coalesce(p_assigned_department_reference, '')), '');
    p_assigned_user_reference := nullif(btrim(coalesce(p_assigned_user_reference, '')), '');

    if p_actor_reference = '' or char_length(p_actor_reference) > 200 then
        raise exception using errcode = '22023', message = 'A valid incident actor reference is required.';
    end if;
    if p_notes is not null and (char_length(p_notes) > 2000 or p_notes ~ '[<>]') then
        raise exception using errcode = '22023', message = 'The incident action note is invalid.';
    end if;
    if p_assigned_department_reference is not null
       and char_length(p_assigned_department_reference) > 200 then
        raise exception using errcode = '22023', message = 'The department reference is invalid.';
    end if;
    if p_assigned_user_reference is not null
       and char_length(p_assigned_user_reference) > 200 then
        raise exception using errcode = '22023', message = 'The user reference is invalid.';
    end if;

    select * into incident_record
    from public.drrm_incidents
    where id = p_incident_id
    for update;

    if not found then
        raise exception using errcode = 'P0002', message = 'The incident could not be found.';
    end if;

    case p_action
        when 'REVIEW' then
            if incident_record.status <> 'SUBMITTED' then
                raise exception using errcode = '23514', message = 'Only a submitted incident can enter review.';
            end if;
            target_status := 'UNDER_REVIEW';
            log_action_type := 'REVIEW_NOTE';
        when 'VERIFY' then
            if incident_record.status <> 'UNDER_REVIEW' then
                raise exception using errcode = '23514', message = 'Only an incident under review can be verified.';
            end if;
            target_status := 'VERIFIED';
            log_action_type := 'VERIFICATION_NOTE';
        when 'ASSIGN' then
            if incident_record.status <> 'VERIFIED' then
                raise exception using errcode = '23514', message = 'Only a verified incident can be assigned.';
            end if;
            if p_assigned_department_reference is null and p_assigned_user_reference is null then
                raise exception using errcode = '22023', message = 'A department or user assignment reference is required.';
            end if;
            target_status := 'ASSIGNED';
            log_action_type := 'ASSIGNMENT_NOTE';
        when 'RESOLVE' then
            if incident_record.status <> 'RESPONDING' then
                raise exception using errcode = '23514', message = 'Only an incident with an active response can be resolved.';
            end if;
            if p_notes is null then
                raise exception using errcode = '22023', message = 'A resolution note is required.';
            end if;
            target_status := 'RESOLVED';
            log_action_type := 'RESOLUTION_NOTE';
        when 'CLOSE' then
            if incident_record.status <> 'RESOLVED' then
                raise exception using errcode = '23514', message = 'Only a resolved incident can be closed.';
            end if;
            target_status := 'CLOSED';
            log_action_type := 'CLOSURE_NOTE';
        when 'REJECT' then
            if incident_record.status not in ('SUBMITTED', 'UNDER_REVIEW') then
                raise exception using errcode = '23514', message = 'This incident can no longer be rejected.';
            end if;
            if p_notes is null then
                raise exception using errcode = '22023', message = 'A rejection reason is required.';
            end if;
            target_status := 'REJECTED';
            log_action_type := 'REJECTION_NOTE';
        else
            raise exception using errcode = '22023', message = 'The incident lifecycle action is invalid.';
    end case;

    if p_action <> 'ASSIGN'
       and (p_assigned_department_reference is not null or p_assigned_user_reference is not null) then
        raise exception using errcode = '22023', message = 'Assignment references are only accepted for assignment actions.';
    end if;

    update public.drrm_incidents
    set status = target_status,
        verification_status = case
            when p_action = 'REVIEW' then 'IN_REVIEW'
            when p_action = 'VERIFY' then 'VERIFIED'
            when p_action = 'REJECT' then 'REJECTED'
            else verification_status
        end,
        verified_at = case when p_action = 'VERIFY' then now() else verified_at end,
        verified_by_reference = case when p_action = 'VERIFY' then p_actor_reference else verified_by_reference end,
        assigned_department_reference = case
            when p_action = 'ASSIGN' then p_assigned_department_reference
            else assigned_department_reference
        end,
        assigned_user_reference = case
            when p_action = 'ASSIGN' then p_assigned_user_reference
            else assigned_user_reference
        end,
        resolved_at = case when p_action = 'RESOLVE' then now() else resolved_at end,
        closed_at = case when p_action = 'CLOSE' then now() else closed_at end
    where id = p_incident_id
      and status = incident_record.status;

    if not found then
        raise exception using errcode = '40001', message = 'The incident changed before the action completed.';
    end if;

    insert into public.drrm_incident_status_history (
        incident_id, from_status, to_status, changed_by_reference, notes
    ) values (
        p_incident_id, incident_record.status, target_status, p_actor_reference, p_notes
    );

    if p_action = 'ASSIGN' then
        insert into public.drrm_incident_assignments (
            incident_id, department_reference, user_reference,
            assigned_by_reference, notes
        ) values (
            p_incident_id, p_assigned_department_reference,
            p_assigned_user_reference, p_actor_reference, p_notes
        );
    end if;

    if p_notes is not null then
        insert into public.drrm_incident_response_logs (
            incident_id, action_type, message, created_by_reference
        ) values (
            p_incident_id, log_action_type, p_notes, p_actor_reference
        );
    end if;

    return jsonb_build_object(
        'id', p_incident_id,
        'incident_number', incident_record.incident_number,
        'previous_status', incident_record.status,
        'status', target_status
    );
end;
$function$;

create or replace function public.add_drrm_incident_response(
    p_incident_id uuid,
    p_action_type text,
    p_message text,
    p_actor_reference text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
    incident_record public.drrm_incidents%rowtype;
    final_status text;
begin
    p_action_type := upper(btrim(coalesce(p_action_type, '')));
    p_message := btrim(coalesce(p_message, ''));
    p_actor_reference := btrim(coalesce(p_actor_reference, ''));

    if p_action_type not in ('DISPATCH_NOTE', 'RESPONSE_UPDATE') then
        raise exception using errcode = '22023', message = 'The response action type is invalid.';
    end if;
    if p_message = '' or char_length(p_message) > 5000 or p_message ~ '[<>]' then
        raise exception using errcode = '22023', message = 'The response message is invalid.';
    end if;
    if p_actor_reference = '' or char_length(p_actor_reference) > 200 then
        raise exception using errcode = '22023', message = 'A valid incident actor reference is required.';
    end if;

    select * into incident_record
    from public.drrm_incidents
    where id = p_incident_id
    for update;

    if not found then
        raise exception using errcode = 'P0002', message = 'The incident could not be found.';
    end if;
    if incident_record.status not in ('ASSIGNED', 'RESPONDING') then
        raise exception using errcode = '23514', message = 'Response updates require an assigned or responding incident.';
    end if;
    if incident_record.status = 'ASSIGNED' and p_action_type <> 'DISPATCH_NOTE' then
        raise exception using errcode = '23514', message = 'The first response entry must be a dispatch note.';
    end if;

    final_status := incident_record.status;
    if incident_record.status = 'ASSIGNED' then
        update public.drrm_incidents
        set status = 'RESPONDING'
        where id = p_incident_id and status = 'ASSIGNED';

        if not found then
            raise exception using errcode = '40001', message = 'The incident changed before the response was recorded.';
        end if;

        insert into public.drrm_incident_status_history (
            incident_id, from_status, to_status, changed_by_reference, notes
        ) values (
            p_incident_id, 'ASSIGNED', 'RESPONDING', p_actor_reference, p_message
        );
        final_status := 'RESPONDING';
    end if;

    insert into public.drrm_incident_response_logs (
        incident_id, action_type, message, created_by_reference
    ) values (
        p_incident_id, p_action_type, p_message, p_actor_reference
    );

    return jsonb_build_object(
        'id', p_incident_id,
        'incident_number', incident_record.incident_number,
        'previous_status', incident_record.status,
        'status', final_status,
        'action_type', p_action_type
    );
end;
$function$;

create or replace function public.drrm_incident_summary()
returns jsonb
language sql
stable
security definer
set search_path = pg_catalog, public
as $function$
    select jsonb_build_object(
        'submitted', count(*) filter (where status = 'SUBMITTED'),
        'under_review', count(*) filter (where status = 'UNDER_REVIEW'),
        'active_response', count(*) filter (where status in ('ASSIGNED', 'RESPONDING')),
        'resolved_today', count(*) filter (
            where resolved_at is not null
              and (resolved_at at time zone 'Asia/Manila')::date
                  = (now() at time zone 'Asia/Manila')::date
        ),
        'total', count(*)
    )
    from public.drrm_incidents;
$function$;

alter table public.drrm_incident_types enable row level security;
alter table public.drrm_incident_severities enable row level security;
alter table public.drrm_incidents enable row level security;
alter table public.drrm_incident_status_history enable row level security;
alter table public.drrm_incident_assignments enable row level security;
alter table public.drrm_incident_response_logs enable row level security;

revoke all on table public.drrm_incident_types from public, anon, authenticated;
revoke all on table public.drrm_incident_severities from public, anon, authenticated;
revoke all on table public.drrm_incidents from public, anon, authenticated;
revoke all on table public.drrm_incident_status_history from public, anon, authenticated;
revoke all on table public.drrm_incident_assignments from public, anon, authenticated;
revoke all on table public.drrm_incident_response_logs from public, anon, authenticated;
revoke all on sequence public.drrm_incident_number_seq from public, anon, authenticated;
revoke all on sequence public.drrm_incident_types_incident_type_id_seq from public, anon, authenticated;
revoke all on sequence public.drrm_incident_severities_severity_id_seq from public, anon, authenticated;

grant select on table public.drrm_incident_types to service_role;
grant select on table public.drrm_incident_severities to service_role;
grant select, insert on table public.drrm_incidents to service_role;
grant select on table public.drrm_incident_status_history to service_role;
grant select on table public.drrm_incident_assignments to service_role;
grant select on table public.drrm_incident_response_logs to service_role;
grant usage, select on sequence public.drrm_incident_types_incident_type_id_seq to service_role;
grant usage, select on sequence public.drrm_incident_severities_severity_id_seq to service_role;

revoke all on function public.next_drrm_incident_number() from public, anon, authenticated;
revoke all on function public.set_module3_updated_at() from public, anon, authenticated;
revoke all on function public.record_drrm_incident_submission() from public, anon, authenticated;
revoke all on function public.validate_drrm_incident_barangay() from public, anon, authenticated;
revoke all on function public.transition_drrm_incident(uuid, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.add_drrm_incident_response(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.drrm_incident_summary() from public, anon, authenticated;

grant execute on function public.next_drrm_incident_number() to service_role;
grant execute on function public.transition_drrm_incident(uuid, text, text, text, text, text) to service_role;
grant execute on function public.add_drrm_incident_response(uuid, text, text, text) to service_role;
grant execute on function public.drrm_incident_summary() to service_role;

insert into public.drrm_incident_types (code, label, sort_order, is_active)
values
    ('FLOOD', 'Flood', 1, true),
    ('FIRE', 'Fire', 2, true),
    ('LANDSLIDE', 'Landslide', 3, true),
    ('EARTHQUAKE', 'Earthquake', 4, true),
    ('ROAD_BLOCKAGE', 'Road Blockage', 5, true),
    ('FALLEN_TREE', 'Fallen Tree', 6, true),
    ('STRUCTURAL_DAMAGE', 'Structural Damage', 7, true),
    ('MEDICAL_EMERGENCY', 'Medical Emergency', 8, true),
    ('UTILITY_HAZARD', 'Utility Hazard', 9, true),
    ('OTHER', 'Other', 10, true)
on conflict (code) do nothing;

insert into public.drrm_incident_severities (code, label, severity_rank, is_active)
values
    ('LOW', 'Low', 1, true),
    ('MODERATE', 'Moderate', 2, true),
    ('HIGH', 'High', 3, true),
    ('CRITICAL', 'Critical', 4, true)
on conflict (code) do nothing;

create or replace function public.verify_module3_incident_schema()
returns jsonb
language sql
stable
security definer
set search_path = pg_catalog, public
as $function$
    with target_tables as (
        select c.relname, c.relrowsecurity
        from pg_catalog.pg_class as c
        join pg_catalog.pg_namespace as n on n.oid = c.relnamespace
        where n.nspname = 'public'
          and c.relkind = 'r'
          and c.relname in (
              'drrm_incident_types', 'drrm_incident_severities',
              'drrm_incidents', 'drrm_incident_status_history',
              'drrm_incident_assignments', 'drrm_incident_response_logs'
          )
    ),
    target_roles as (
        select unnest(array['anon', 'authenticated']) as role_name
    ),
    target_table_names as (
        select unnest(array[
            'drrm_incident_types', 'drrm_incident_severities',
            'drrm_incidents', 'drrm_incident_status_history',
            'drrm_incident_assignments', 'drrm_incident_response_logs'
        ]) as table_name
    )
    select jsonb_build_object(
        'tables_exist', (select count(*) = 6 from target_tables),
        'rls_enabled', (select count(*) = 6 and bool_and(relrowsecurity) from target_tables),
        'direct_client_privileges_restricted', not exists (
            select 1
            from target_roles cross join target_table_names
            where has_table_privilege(
                target_roles.role_name,
                'public.' || target_table_names.table_name,
                'SELECT,INSERT,UPDATE,DELETE'
            )
        ),
        'policy_count', (
            select count(*)
            from pg_catalog.pg_policies
            where schemaname = 'public'
              and tablename in (select table_name from target_table_names)
        ),
        'incident_type_count', (select count(*) from public.drrm_incident_types),
        'incident_type_seed_valid', (
            select count(*) = 10
            from public.drrm_incident_types
            where code in (
                'FLOOD', 'FIRE', 'LANDSLIDE', 'EARTHQUAKE', 'ROAD_BLOCKAGE',
                'FALLEN_TREE', 'STRUCTURAL_DAMAGE', 'MEDICAL_EMERGENCY',
                'UTILITY_HAZARD', 'OTHER'
            ) and is_active
        ),
        'severity_count', (select count(*) from public.drrm_incident_severities),
        'severity_seed_valid', (
            select count(*) = 4
            from public.drrm_incident_severities
            where code in ('LOW', 'MODERATE', 'HIGH', 'CRITICAL') and is_active
        ),
        'incident_count', (select count(*) from public.drrm_incidents),
        'status_history_count', (select count(*) from public.drrm_incident_status_history),
        'assignment_count', (select count(*) from public.drrm_incident_assignments),
        'response_log_count', (select count(*) from public.drrm_incident_response_logs),
        'warning_trigger_count', (
            select count(*)
            from pg_catalog.pg_trigger as trigger_record
            join pg_catalog.pg_class as table_record on table_record.oid = trigger_record.tgrelid
            where table_record.relname = 'drrm_incidents'
              and pg_catalog.pg_get_triggerdef(trigger_record.oid) ilike '%early_warning%'
              and not trigger_record.tgisinternal
        )
    );
$function$;

revoke all on function public.verify_module3_incident_schema() from public, anon, authenticated;
grant execute on function public.verify_module3_incident_schema() to service_role;

notify pgrst, 'reload schema';

commit;
